name: CI

on: [push, pull_request]

jobs:
  eslint-build-run:
    name: ESLint, Build, and Run
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: ESLint Check
      run: npx eslint --ext .js,.ts,.jsx,.tsx

    - name: Build React app
      run: npm run build
