name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  eslint-build-run:
    name: ESLint, Build, and Run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Clear cache
        run: yarn cache clean

      - name: Install dependencies
        run: yarn install

      - name: ESLint Check
        run: yarn lint

      - name: Build React app
        run: yarn run build
