name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  eslint-build-run:
    name: 'Frontend: ESLint, Build, and Run'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: frontend

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('frontend/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
  
      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        name: List the state of node modules
        continue-on-error: true
        run: yarn --cwd frontend list

      - name: Install dependencies
        run: yarn --cwd frontend install

      - name: ESLint Check
        run: yarn --cwd frontend lint

      - name: Build React app
        run: yarn --cwd frontend run build
